select ID,SDKKD,OWNER,SUB_OWNER,SOURCE,SUB_SOURCE,BD_USERNAME,HL_USERNAME,TL_USERNAME,
SALER_USERNAME,DAO,TEAM,BOOK_ID,STATUS,PREVIOUS_STATUS,MAX_TIMEOUT,
TO_CHAR(MAX_TIMEOUT_DATE,'YYYY-MM-DD HH:MI:SS') MAX_TIMEOUT_DATE,MAX_EXPLOITATION,TO_CHAR(MAX_EXPLOITATION_DATE,'YYYY-MM-DD HH:MI:SS') MAX_EXPLOITATION_DATE,CONTACT_NAME,CONTACT_PHONE,
CONTACT_EMAIL,COMPANY_NAME,SEGMENT_SME,COMPANY_ADDRESS,COMPANY_ANNUAL_REVENUE,
COMPANY_BUSSINESS_LINE,COMPANY_SIZE,REGISTER_DATE,CUSTOMER_NEED,IS_BLACK_LEAD,CAN_ASSIGN,
CAN_RECALL,IS_LINK_CLOS,TO_CHAR(LAST_CONTACT_DATE,'YYYY-MM-DD HH:MI:SS') LAST_CONTACT_DATE,TO_CHAR(NEXT_APPOINTMENT_DATE,'YYYY-MM-DD HH:MI:SS') NEXT_APPOINTMENT_DATE,TO_CHAR(LAST_EXPLOITATION_DATE,'YYYY-MM-DD HH:MI:SS') LAST_EXPLOITATION_DATE,
LAST_RECALL_DATE,LAST_ADDING_PRODUCT_DATE,MODIFY_USERNAME,TOTAL_SPECIAL_OFFER,
ACCOUNT_NUMBER,BOOK_SME_ONLINE,DAO_SME_ONLINE,REQUEST_CHANGE_DAO,CUSTOMER_REGISTER_DATE,CIF,
TO_CHAR(CIF_OPEN_DATE,'YYYY-MM-DD HH:MI:SS') CIF_OPEN_DATE,
BOOK_CIF,DAO_CIF,T24_BUSSINESS_LINE,T24_BUSSINESS_SIZE,
TO_CHAR(CREATED_AT,'YYYY-MM-DD HH:MI:SS') CREATED_AT,TO_CHAR(UPDATED_AT,'YYYY-MM-DD HH:MI:SS') UPDATED_AT,
TO_CHAR(LAST_ASSIGN_DATE,'YYYY-MM-DD HH:MI:SS') LAST_ASSIGN_DATE,ACCOUNT_STATUS,
CLOS_OPEN_DATE,LAST_ADD_PRODUCT_DATE,FINAL_STATUS
from SME_V2_CUSTOMERS
where TRUNC(UPDATED_AT) >= to_date('01-01-2020','DD/MM/YYYY')

-- END --

select ID,ACTION_NAME,CUSTOMER_ID,SDKKD,BD_USERNAME,HL_USERNAME,TL_USERNAME,SALER_USERNAME,DAO,
TEAM,BOOK_ID,CUSTOMER_NEED,NOTE,SEGMENT_SME,MAX_TIMEOUT,MAX_TIMEOUT_DATE,MAX_EXPLOITATION,
MAX_EXPLOITATION_DATE,RESULT,PRODUCT_HOLDINGS,NEXT_APPOINTMENT_DATE,
"RESOURCE",NEW_RESOURCE,TO_CHAR(CREATED_AT,'YYYY-MM-DD HH:MI:SS') CREATED_AT,TO_CHAR(UPDATED_AT,'YYYY-MM-DD HH:MI:SS') UPDATED_AT,CIF,DAO_CIF,CIF_USERNAME
from SME_V2_CUSTOMER_HISTORIES
where TRUNC(UPDATED_AT) >= to_date('01-01-2020','DD/MM/YYYY')

-- END --

select USERNAME,EMAIL,TITLE,FULLNAME,DAO,TEAM,BOOK_ID,REGION,CHANNEL,USER_ROLE,USER_STATUS,
CREATED_BY,MODIFY_BY,IS_ACCESS_DEVICE,IS_REQUIRED_RULE_CLOS,
TO_CHAR(CREATED_AT,'YYYY-MM-DD HH:MI:SS') CREATED_AT,
TO_CHAR(UPDATED_AT,'YYYY-MM-DD HH:MI:SS') UPDATED_AT,BOOK,TEAM_ID,TEAM_LIST,
SEGMENT_MICRO,SEGMENT_NON_MICRO
from SME_V2_USERS

-- END --

select USERNAME,RESOURCE_CODE,
TO_CHAR(CREATED_AT,'YYYY-MM-DD HH:MI:SS') CREATED_AT,
TO_CHAR(UPDATED_AT,'YYYY-MM-DD HH:MI:SS') UPDATED_AT
from SME_V2_USER_RESOURCES 

-- END --

select DEPARTMENT_NAME,DEPARTMENT_CODE,DEPARTMENT_CODE_VN,DEPARTMENT_TYPE,MANAGER_DAO,MANAGER_EMAIL,MANAGER_USERNAME,
TO_CHAR(CREATED_AT,'YYYY-MM-DD HH:MI:SS') CREATED_AT,
TO_CHAR(UPDATED_AT,'YYYY-MM-DD HH:MI:SS') UPDATED_AT,MANAGER_FULLNAME
from SME_DEPARTMENT

-- END --

select CODE,TO_CHAR(CREATED_AT,'YYYY-MM-DD HH:MI:SS') CREATED_AT,
TO_CHAR(UPDATED_AT,'YYYY-MM-DD HH:MI:SS') UPDATED_AT,status
from SME_V2_RESOURCES 
 
-- END --

select DEPARTMENT_ID,USER_NAME,DAO,ACTION,TO_CHAR(DATETIME,'YYYY-MM-DD HH:MI:SS')DATETIME,LASTING,ACTION_GROUP,IMEI,IP,
TO_CHAR(CREATED_AT,'YYYY-MM-DD HH:MI:SS')CREATED_AT,
TO_CHAR(UPDATED_AT,'YYYY-MM-DD HH:MI:SS')UPDATED_AT,DEPARTMENT_NAME
from sme_logs_action
where TRUNC(DATETIME) >= to_date('01-01-2021','DD/MM/YYYY') and TRUNC(DATETIME) <= to_date('31-01-2021','DD/MM/YYYY')

 